# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install --production

# Copy source files
COPY . ./

# Set production environment
ENV NODE_ENV=production

# Start the MCP server
CMD ["node", "src/index.mjs"]
